### ISSUE TITLE
 Container for service "lotus-miner" is unhealthy and fails to start

### ISSUE THREAD

**Issue by xlassix** [filecoin-project/filecoin-fvm-localnet#10]
**Description:**
I recently experienced an issue with the Docker container running the "lotus-miner" service. Upon tearing down the compose setup using docker-compose down, I've been unable to bring it back up due to an error stating that the container for the "lotus-miner" service is unhealthy.

**Steps to reproduce:**
Ran docker-compose down to tear down the running setup.
Attempted to bring the setup back up using docker-compose up.
Expected result:
The "lotus-miner" service container should have started normally without any issues.

**Comment by hammertoe** [comment]
Thanks! I'm not sure what has caused this, it may be a timing issue. I've updated to newest version of Lotus and Boost and added extra startup checks, so please try with latest version and re-open issue if still a problem.
